steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]

  - name: golangci/golangci-lint
    args:
      - golangci-lint
      - run
      - /src/*/**
      - --issues-exit-code=0 #don't fail the build
    volumes:
    - name: 'go-modules'
      path: /go
    id: 'run lint'


  # - id: go_test
  #   name: "gcr.io/cloud-builders/go"
  #   args: ["test","helloworld"]
  #   env: ["GOPATH=."]

  # - id: go_security
  #   name: "securego/gosec"
  #   args: ["helloworld"]
  #   env: ["GOPATH=."]

  - id: run_app
    name: "gcr.io/cloud-builders/go"
    args: ["run","./src/timechecker/main.go"]
    env: ["GOPATH=./"]