steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]

  - name: golangci/golangci-lint

  - id: run_app
    name: "gcr.io/cloud-builders/go"
    args: ["run","./src/timechecker/main.go"]
    env: ["GOPATH=./"]